site_name: Kunoichi Wiki
site_description: 'Documentation for the Kunoichi Wiki'
site_author: 'Settius'
docs_dir: docs/
repo_name: 'Settius/Kunoichi_Wiki'
repo_url: 'https://github.com/Settius/Kunoichi_Wiki'
copyright : Copyright &copy; 2020-2021 Puny Human
extra_css:
  - stylesheets/extra.css
nav:
    - Home: 
        - Home: index.md
    - "Notes":
      - Home: "notes/index.md"
      - "Star Wars Jedi: Fallen Order": "notes/fallen_order.md"
      - "Uncharted 4": "notes/uncharted4.md"
      - "God of War Ragnarok": "gow_ragnaraok.md"
      - "Rise of the Tomb Raider": "notes/rise_tomb_raider.md"
      - "Carrion": "notes/carrion.md"
      - "Haak": "notes/haak.md"      
      - "Steamworld Dig": "notes/steamworld_dig.md"  
      - "Yoku's Island Express": "notes/yoku.md"
      - "Stray": "notes/stray.md"
      - "Gunk": "notes/gunk.md"
      - "Junky Games": "notes/junky_games.md"
      - "Fez" : "notes/fex.md"
    - "Arc Inventory":
      - Home: "arcinventory/index.md"
      - "Initial Setup": "arcinventory/initialsetup.md"
      - "Concepts":
          - "High Level": "arcinventory/concepts/highlevel.md"
          - "Inventory": "arcinventory/concepts/inventory.md"
          - "Item Stacks": "arcinventory/concepts/itemstack.md"
          - "Item Generators": "arcinventory/concepts/generators.md"
          - "User Interface": "arcinventory/concepts/ui.md"
      - Tutorials:
        - "Simple FPS": "arcinventory/tutorials/simplefps.md"
        - "Maniuplating Items": "arcinventory/tutorials/containers.md"
        - "Randomized Item Generation": "arcinventory/tutorials/randomitems.md"
      - Integrations:
        - "MoveIt": "arcinventory/integrations/moveit.md"
      - "Useful Resources": "arcinventory/usefulresources.md"
      - Changelogs:
        - "arcinventory/changelogs/1.4.2.174.md"
        - "arcinventory/changelogs/1.4.1.163.md"
        - "arcinventory/changelogs/1.4.0.157.md"
        - "arcinventory/changelogs/1.3.3.150.md"
        - "arcinventory/changelogs/1.3.2.145.md"
        - "arcinventory/changelogs/1.3.1.144.md"
        - "arcinventory/changelogs/1.3.0.138.md"
        - "arcinventory/changelogs/1.2.9.134.md"
        - "arcinventory/changelogs/1.2.8.132.md"
        - "arcinventory/changelogs/1.2.7.131.md"
        - "arcinventory/changelogs/1.2.6.129.md"
        - 'arcinventory/changelogs/1.2.5.123.md'
        - 'arcinventory/changelogs/1.2.4.118.md'
        - 'arcinventory/changelogs/1.2.3.115.md'
        - 'arcinventory/changelogs/1.2.2.113.md'
        - 'arcinventory/changelogs/1.2.1.106.md'
        - 'arcinventory/changelogs/1.2.0.md'
      - "FAQ/Common Issues": "arcinventory/faq.md"
    - "Arc Teams":
        - Home: "arcteams/index.md"
        - "Initial Setup": "arcteams/initialsetup.md"
        - "Debug Aids": "arcteams/debugaids.md"
        - Concepts:
          - "High Level": "arcteams/concepts/highlevel.md"
          - "Teams": "arcteams/concepts/team.md"
          - "Team Components": "arcteams/concepts/teamcomponents.md"
        - Changelog:
          - "arcteams/changelog/1.3.0.98.md"
          - "arcteams/changelog/1.2.1.86.md"          
    - "Arc Communication":
      - Home: "arccommunication/index.md"
      - Concepts:
        - "Routers": "arccommunication/concepts/routers.md"
        - "Localized Messages": "arccommunication/concepts/localizedmessages.md"
        - "Voice": "arccommunication/concepts/voip.md"
        - "User Interface": "arccommunication/concepts/ui.md"
theme:
  name: 'material'
  palette:
    scheme: punyhuman
  features:
    - navigation.tabs
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - def_list
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
